//! Deadline-driven Opus packet-loss concealment.
//!
//! The jitter buffer decides when a frame is due; this module makes that
//! decision audible. A missing frame is first recovered from the following
//! packet's in-band FEC data when available, then falls back to Opus PLC.
//! Neither path waits for a late packet.

use anyhow::{Context, Result};
use opus::{Channels, Decoder};

use super::jitter::{AudioJitterBuffer, AudioPlayout};
use crate::call::frame::{SAMPLES_PER_FRAME, SAMPLE_RATE};

/// One decoded frame ready for the playback queue.
#[derive(Debug, Clone, PartialEq)]
pub struct DecodedAudioFrame {
    /// Sequence number represented by this PCM frame.
    pub sequence: u32,
    /// Mono normalized PCM samples at [`SAMPLE_RATE`].
    pub samples: Vec<f32>,
    /// True when the frame was generated by Opus FEC or PLC.
    pub concealed: bool,
    /// True specifically when in-band FEC recovered the frame.
    pub used_fec: bool,
}

/// Stateful decoder for one 48 kHz mono call track.
#[derive(Debug)]
pub struct OpusPlayoutDecoder {
    decoder: Decoder,
}

impl OpusPlayoutDecoder {
    /// Create a decoder matching the initial voice-call profile.
    pub fn new() -> Result<Self> {
        Ok(Self {
            decoder: Decoder::new(SAMPLE_RATE, Channels::Mono)
                .context("create Opus playback decoder")?,
        })
    }

    /// Decode one due jitter-buffer item without waiting for network input.
    ///
    /// For a missing sequence, the immediately following buffered packet is
    /// offered to Opus with `fec = true`. The following packet remains in the
    /// jitter buffer and is decoded normally on its own deadline.
    pub fn decode_due(
        &mut self,
        buffer: &mut AudioJitterBuffer,
        now: std::time::Instant,
    ) -> Result<Option<DecodedAudioFrame>> {
        let playout = match buffer.pop_due(now) {
            Some(playout) => playout,
            None => return Ok(None),
        };
        match playout {
            AudioPlayout::Packet(packet) => {
                let samples = self.decode(&packet.payload, false)?;
                Ok(Some(DecodedAudioFrame {
                    sequence: packet.sequence,
                    samples,
                    concealed: false,
                    used_fec: false,
                }))
            }
            AudioPlayout::Missing { sequence } => {
                let next = sequence.wrapping_add(1);
                let mut samples = vec![0.0; SAMPLES_PER_FRAME];
                if let Some(packet) = buffer.peek(next) {
                    if let Ok(count) =
                        self.decoder
                            .decode_float(&packet.payload, &mut samples, true)
                    {
                        samples.truncate(count);
                        return Ok(Some(DecodedAudioFrame {
                            sequence,
                            samples,
                            concealed: true,
                            used_fec: true,
                        }));
                    }
                }

                // An empty Opus packet asks libopus for packet-loss
                // concealment. Keep this path bounded to one frame.
                let count = self
                    .decoder
                    .decode_float(&[], &mut samples, false)
                    .context("Opus packet-loss concealment")?;
                samples.truncate(count);
                Ok(Some(DecodedAudioFrame {
                    sequence,
                    samples,
                    concealed: true,
                    used_fec: false,
                }))
            }
        }
    }

    fn decode(&mut self, payload: &[u8], fec: bool) -> Result<Vec<f32>> {
        let mut samples = vec![0.0; SAMPLES_PER_FRAME];
        let count = self
            .decoder
            .decode_float(payload, &mut samples, fec)
            .context("decode Opus audio packet")?;
        samples.truncate(count);
        Ok(samples)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::call::audio::codec::OpusEncoder;
    use crate::call::audio::jitter::{
        BufferedAudioPacket, AUDIO_FRAME_DURATION, DEFAULT_JITTER_DELAY,
    };
    use crate::call::CallId;
    use std::time::Instant;

    fn packet(
        call_id: CallId,
        sequence: u32,
        arrival: Instant,
        payload: Vec<u8>,
    ) -> BufferedAudioPacket {
        BufferedAudioPacket {
            call_id,
            sequence,
            timestamp: sequence * SAMPLES_PER_FRAME as u32,
            arrival,
            payload,
        }
    }

    fn encoded_frames() -> Vec<Vec<u8>> {
        let mut encoder = OpusEncoder::new().unwrap();
        (0..3)
            .map(|frame| {
                let pcm: Vec<f32> = (0..SAMPLES_PER_FRAME)
                    .map(|sample| ((sample + frame * 17) as f32 * 0.03).sin() * 0.3)
                    .collect();
                encoder.encode(&pcm).unwrap().unwrap()
            })
            .collect()
    }

    #[test]
    fn missing_packet_returns_non_empty_plc_and_advances() {
        let call = CallId::from_bytes([1; 16]);
        let start = Instant::now();
        let frames = encoded_frames();
        let mut buffer = AudioJitterBuffer::default();
        assert!(buffer.push(packet(call, 0, start, frames[0].clone())));
        assert!(buffer.push(packet(call, 2, start, frames[2].clone())));
        let mut decoder = OpusPlayoutDecoder::new().unwrap();
        assert_eq!(
            decoder
                .decode_due(&mut buffer, start + DEFAULT_JITTER_DELAY)
                .unwrap()
                .unwrap()
                .sequence,
            0
        );
        let concealed = decoder
            .decode_due(
                &mut buffer,
                start + DEFAULT_JITTER_DELAY + AUDIO_FRAME_DURATION,
            )
            .unwrap()
            .unwrap();
        assert_eq!(concealed.sequence, 1);
        assert!(concealed.concealed);
        assert!(!concealed.samples.is_empty());
        assert_eq!(buffer.missing_packets(), 1);
    }

    #[test]
    fn next_packet_fec_is_used_when_available() {
        let call = CallId::from_bytes([2; 16]);
        let start = Instant::now();
        let frames = encoded_frames();
        let mut buffer = AudioJitterBuffer::default();
        assert!(buffer.push(packet(call, 0, start, frames[0].clone())));
        assert!(buffer.push(packet(call, 2, start, frames[2].clone())));
        let mut decoder = OpusPlayoutDecoder::new().unwrap();
        decoder
            .decode_due(&mut buffer, start + DEFAULT_JITTER_DELAY)
            .unwrap();
        let concealed = decoder
            .decode_due(
                &mut buffer,
                start + DEFAULT_JITTER_DELAY + AUDIO_FRAME_DURATION,
            )
            .unwrap()
            .unwrap();
        assert!(
            concealed.used_fec,
            "the following Opus packet should supply FEC"
        );
    }

    #[test]
    fn invalid_fec_packet_falls_back_to_plc_immediately() {
        let call = CallId::from_bytes([3; 16]);
        let start = Instant::now();
        let frames = encoded_frames();
        let mut buffer = AudioJitterBuffer::default();
        assert!(buffer.push(packet(call, 0, start, frames[0].clone())));
        assert!(buffer.push(packet(call, 2, start, vec![0xff])));
        let mut decoder = OpusPlayoutDecoder::new().unwrap();
        let first = decoder
            .decode_due(&mut buffer, start + DEFAULT_JITTER_DELAY)
            .unwrap()
            .unwrap();
        assert!(!first.concealed);
        let concealed = decoder
            .decode_due(
                &mut buffer,
                start + DEFAULT_JITTER_DELAY + AUDIO_FRAME_DURATION,
            )
            .unwrap()
            .unwrap();
        assert!(concealed.concealed);
        assert!(!concealed.used_fec);
        assert!(!concealed.samples.is_empty());
    }
}
