//! Central file-type resolver for Boru (PAPIRUS-05).
//!
//! Every Boru file-sharing surface that shows a file or folder icon must
//! select that icon through [`resolve_file_icon`].  Individual screens must
//! **not** keep their own extension maps: this module is the single source
//! of truth for "which bundled Papirus icon represents this file".
//!
//! ## Resolution priority
//!
//! The resolver evaluates inputs in this exact order:
//!
//! 1. Explicit directory / folder state
//! 2. Trusted MIME type detected locally after download
//! 3. Validated MIME type already known from the local sharing source
//! 4. Advertised MIME type received from a peer (treated as a **hint**, not truth)
//! 5. Compound filename extension (`.tar.gz`, `.d.ts`, ...)
//! 6. Ordinary filename extension (`.pdf`, `.png`, ...)
//! 7. Broad category fallback (e.g. `video/*` → `Video`)
//! 8. Generic unknown-file fallback
//!
//! The public API collapses priorities 2 and 3 into the single
//! `locally_detected_mime_type` parameter: the caller passes whichever
//! trusted local MIME it has (post-download detection or validated local
//! source).  Both outrank the peer-advertised hint.
//!
//! ## Never a missing asset
//!
//! The resolver embeds the pinned Papirus manifest (PAPIRUS-02/03) and
//! consults it before returning: every candidate icon is checked against
//! the bundled asset set, and the fallback chain walks
//! *exact icon → related extension icon → broad category icon → unknown
//! generic icon*, where the terminal unknown icon is one of the manifest's
//! guaranteed `required_fallbacks`.  A `ResolvedFileIcon::asset_path` is
//! therefore always a path that exists in the pinned bundle.
//!
//! ## Peer MIME is a hint
//!
//! A peer-provided MIME never renames, executes, or opens a file.  When it
//! conflicts strongly with a locally detected type, the resolver prefers
//! the locally detected type for the icon, records the mismatch through the
//! existing `tracing` diagnostics channel (`tracing::warn!`), and exposes
//! the mismatch on [`ResolvedFileIcon::mime_mismatch`] so the UI can show a
//! warning state.
//!
//! ## Scope of this module
//!
//! The mapping tables below are the initial seed set.  PAPIRUS-08 extends
//! the MIME → icon mapping and PAPIRUS-09 extends coverage; the resolver
//! core, priority chain, and fallback structure are final.

use std::collections::HashMap;
use std::sync::OnceLock;

use crate::file_category::FileCategory;

// ── Constants ────────────────────────────────────────────────────────

/// Repo-relative root of the bundled Papirus asset set.
pub const PAPIRUS_ASSET_ROOT: &str = "assets/third_party/papirus";

/// Default icon size returned in `ResolvedFileIcon::asset_path`.
///
/// The `FileTypeIcon` component (PAPIRUS-04) is responsible for semantic
/// sizes; the resolver returns the canonical `card` size and the component
/// can re-query `PapirusCatalog::asset_path(icon_id, size)` for others.
pub const DEFAULT_ICON_SIZE: u16 = 32;

/// Embedded copy of the pinned manifest (generated by PAPIRUS-02/03).
const MANIFEST_JSON: &str = include_str!("../../assets/third_party/papirus/manifest.json");

/// Terminal fallback icon; guaranteed present by the manifest's
/// `required_fallbacks` list.
const UNKNOWN_ICON: &str = "application-x-generic";

/// Icon used for explicit directory / folder state.
const DIRECTORY_ICON: &str = "folder-open";

// ── Public types ─────────────────────────────────────────────────────

/// The resolved presentation of a file or folder.
///
/// This is a **local** presentation concern: the category is never
/// transmitted, and no file-transfer payload or message type is modified.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ResolvedFileIcon {
    /// Papirus icon identifier, e.g. `"application-pdf"`.
    pub icon_id: String,
    /// Repo-relative asset path that exists in the pinned bundle, e.g.
    /// `"assets/third_party/papirus/32/application-pdf.svg"`.
    pub asset_path: String,
    /// Coarse presentation category derived during resolution.
    pub file_category: FileCategory,
    /// Human-readable label for tooltips / accessible text.
    pub display_label: String,
    /// How strongly the icon matches the actual file type.
    pub confidence: IconConfidence,
    /// Which priority level won the resolution.
    pub source: ResolutionSource,
    /// Present when a peer-advertised MIME strongly conflicted with a
    /// locally detected MIME (local won for the icon).
    pub mime_mismatch: Option<MimeMismatch>,
}

/// Ordered confidence ladder for a resolved icon.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum IconConfidence {
    /// Explicit directory state or a trusted local MIME type.
    Exact,
    /// Validated local MIME or a compound filename extension.
    Strong,
    /// Advertised (peer-hinted) MIME or an ordinary extension.
    Medium,
    /// Broad category fallback.
    Weak,
    /// Generic unknown-file fallback.
    None,
}

/// Which input won the resolution.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ResolutionSource {
    /// Explicit directory / folder state (priority 1).
    Directory,
    /// Trusted local MIME: detected after download or validated from the
    /// local sharing source (priorities 2–3).
    LocalMime,
    /// Advertised MIME received from a peer (priority 4, a hint).
    AdvertisedMime,
    /// Compound filename extension (priority 5).
    CompoundExtension,
    /// Ordinary filename extension (priority 6).
    Extension,
    /// Broad category fallback (priority 7).
    CategoryFallback,
    /// Generic unknown-file fallback (priority 8).
    UnknownFallback,
}

/// A recorded conflict between a peer-advertised MIME and a locally
/// detected MIME.  The locally detected type wins for the icon.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MimeMismatch {
    /// MIME type advertised by the remote peer.
    pub advertised: String,
    /// MIME type detected or validated locally.
    pub locally_detected: String,
    /// Category derived from the advertised MIME.
    pub advertised_category: FileCategory,
    /// Category derived from the locally detected MIME.
    pub locally_detected_category: FileCategory,
}

// ── Manifest catalog ─────────────────────────────────────────────────

/// Parsed view of the pinned Papirus manifest.
///
/// `icons: icon_id -> (size -> manifest-relative path)`.
#[derive(Debug)]
struct PapirusCatalog {
    icons: HashMap<String, HashMap<u16, String>>,
    required_fallbacks: Vec<String>,
}

static CATALOG: OnceLock<PapirusCatalog> = OnceLock::new();

impl PapirusCatalog {
    /// Access the shared catalog parsed from the embedded manifest.
    fn global() -> &'static PapirusCatalog {
        CATALOG.get_or_init(PapirusCatalog::load)
    }

    fn load() -> Self {
        let value: serde_json::Value =
            serde_json::from_str(MANIFEST_JSON).expect("embedded Papirus manifest must parse");

        let mut icons = HashMap::new();
        if let Some(icons_obj) = value.get("icons").and_then(serde_json::Value::as_object) {
            for (icon_id, sizes) in icons_obj {
                let mut size_map = HashMap::new();
                if let Some(sizes_obj) = sizes.as_object() {
                    for (size, path) in sizes_obj {
                        if let (Ok(size), Some(path)) = (size.parse::<u16>(), path.as_str()) {
                            size_map.insert(size, path.to_string());
                        }
                    }
                }
                icons.insert(icon_id.clone(), size_map);
            }
        }

        let required_fallbacks = value
            .get("required_fallbacks")
            .and_then(serde_json::Value::as_array)
            .map(|arr| {
                arr.iter()
                    .filter_map(serde_json::Value::as_str)
                    .map(str::to_string)
                    .collect()
            })
            .unwrap_or_default();

        PapirusCatalog {
            icons,
            required_fallbacks,
        }
    }

    /// Whether `icon_id` is present in the pinned bundle.
    fn has_icon(&self, icon_id: &str) -> bool {
        self.icons.contains_key(icon_id)
    }

    /// Manifest-relative path for `icon_id` at `size`, e.g.
    /// `"32/application-pdf.svg"`.
    fn manifest_path(&self, icon_id: &str, size: u16) -> Option<&str> {
        self.icons.get(icon_id)?.get(&size).map(String::as_str)
    }

    /// Repo-relative path for `icon_id` at `size`, e.g.
    /// `"assets/third_party/papirus/32/application-pdf.svg"`.
    pub fn asset_path(&self, icon_id: &str, size: u16) -> Option<String> {
        self.manifest_path(icon_id, size)
            .map(|p| format!("{PAPIRUS_ASSET_ROOT}/{p}"))
    }
}

// ── Seed mapping tables (PAPIRUS-08/09 extend) ───────────────────────

/// (extension, icon_id, category) — ordinary extensions.
///
/// Extensions are matched case-insensitively after trimming; compound
/// extensions are checked before ordinary ones.
const EXTENSION_ICONS: &[(&str, &str, FileCategory)] = &[
    // Documents
    ("pdf", "application-pdf", FileCategory::Pdf),
    ("doc", "application-msword", FileCategory::Document),
    (
        "docx",
        "application-vnd.openxmlformats-officedocument.wordprocessingml.document",
        FileCategory::Document,
    ),
    (
        "odt",
        "application-vnd.oasis.opendocument.text",
        FileCategory::Document,
    ),
    ("rtf", "application-rtf", FileCategory::Document),
    // Spreadsheets
    ("xls", "application-vnd.ms-excel", FileCategory::Spreadsheet),
    (
        "xlsx",
        "application-vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        FileCategory::Spreadsheet,
    ),
    (
        "ods",
        "application-vnd.oasis.opendocument.spreadsheet",
        FileCategory::Spreadsheet,
    ),
    ("csv", "text-csv", FileCategory::Spreadsheet),
    // Presentations
    (
        "ppt",
        "application-vnd.ms-powerpoint",
        FileCategory::Presentation,
    ),
    (
        "pptx",
        "application-vnd.openxmlformats-officedocument.presentationml.presentation",
        FileCategory::Presentation,
    ),
    (
        "odp",
        "application-vnd.oasis.opendocument.presentation",
        FileCategory::Presentation,
    ),
    // Text / markdown
    ("txt", "text-plain", FileCategory::Text),
    ("log", "text-x-log", FileCategory::Text),
    ("md", "text-markdown", FileCategory::Markdown),
    ("markdown", "text-markdown", FileCategory::Markdown),
    // Source code
    ("rs", "text-rust", FileCategory::SourceCode),
    ("py", "text-x-python", FileCategory::SourceCode),
    ("js", "application-javascript", FileCategory::SourceCode),
    ("ts", "text-javascript", FileCategory::SourceCode),
    ("html", "text-html", FileCategory::SourceCode),
    ("css", "text-css", FileCategory::SourceCode),
    ("json", "application-json", FileCategory::SourceCode),
    ("xml", "application-xml", FileCategory::SourceCode),
    ("yaml", "application-yaml", FileCategory::SourceCode),
    ("yml", "application-yaml", FileCategory::SourceCode),
    ("toml", "application-toml", FileCategory::SourceCode),
    ("sh", "text-x-shellscript", FileCategory::SourceCode),
    ("sql", "application-sql", FileCategory::SourceCode),
    // Images
    ("png", "image-png", FileCategory::Image),
    ("jpg", "image-jpeg", FileCategory::Image),
    ("jpeg", "image-jpeg", FileCategory::Image),
    ("gif", "image-gif", FileCategory::Image),
    ("bmp", "image-bmp", FileCategory::Image),
    ("svg", "image-svg+xml", FileCategory::Image),
    ("tiff", "image-tiff", FileCategory::Image),
    ("tif", "image-tiff", FileCategory::Image),
    // Video
    ("mp4", "video-mp4", FileCategory::Video),
    ("webm", "video-webm", FileCategory::Video),
    ("mkv", "video-x-matroska", FileCategory::Video),
    ("avi", "video-x-msvideo", FileCategory::Video),
    ("ogv", "video-x-theora+ogg", FileCategory::Video),
    ("m4v", "video-mp4", FileCategory::Video),
    // Audio
    ("mp3", "audio-mp3", FileCategory::Audio),
    ("flac", "audio-flac", FileCategory::Audio),
    ("wav", "audio-x-wav", FileCategory::Audio),
    ("ogg", "audio-x-vorbis+ogg", FileCategory::Audio),
    ("m4a", "audio-x-m4a", FileCategory::Audio),
    ("wma", "audio-x-ms-wma", FileCategory::Audio),
    // Archives
    ("zip", "application-zip", FileCategory::Archive),
    ("7z", "application-x-7z-compressed", FileCategory::Archive),
    ("rar", "application-vnd.rar", FileCategory::Archive),
    ("tar", "application-x-tar", FileCategory::Archive),
    ("gz", "application-gzip", FileCategory::Archive),
    ("bz2", "application-x-bzip2", FileCategory::Archive),
    (
        "xz",
        "application-x-xz-compressed-tar",
        FileCategory::Archive,
    ),
    ("zst", "application-zstd", FileCategory::Archive),
    // Executables / installers / images
    (
        "exe",
        "application-x-ms-dos-executable",
        FileCategory::Executable,
    ),
    (
        "deb",
        "application-vnd.debian.binary-package",
        FileCategory::Installer,
    ),
    ("rpm", "application-x-rpm", FileCategory::Installer),
    (
        "apk",
        "application-vnd.android.package-archive",
        FileCategory::Installer,
    ),
    ("iso", "application-x-cd-image", FileCategory::DiskImage),
    (
        "img",
        "application-x-raw-disk-image",
        FileCategory::DiskImage,
    ),
    (
        "dmg",
        "application-x-apple-diskimage",
        FileCategory::DiskImage,
    ),
    // Databases / fonts / certificates / keys
    ("sqlite", "application-x-sqlite3", FileCategory::Database),
    ("sqlite3", "application-x-sqlite3", FileCategory::Database),
    ("db", "application-x-sqlite3", FileCategory::Database),
    ("ttf", "application-x-font-ttf", FileCategory::Font),
    ("otf", "application-x-font-otf", FileCategory::Font),
    ("crt", "application-certificate", FileCategory::Certificate),
    ("cer", "application-certificate", FileCategory::Certificate),
    ("pem", "application-x-pem-key", FileCategory::Key),
    ("key", "application-pgp-keys", FileCategory::Key),
    // Ebooks / torrents / CAD / 3D
    ("epub", "application-epub+zip", FileCategory::Ebook),
    ("mobi", "application-epub+zip", FileCategory::Ebook),
    ("torrent", "application-x-bittorrent", FileCategory::Torrent),
    ("step", "application-x-step", FileCategory::Cad),
    ("stp", "application-x-step", FileCategory::Cad),
    ("stl", "model-stl", FileCategory::ThreeDimensional),
];

/// Compound extensions checked before ordinary extensions.
///
/// The exact matching behaviour (`archive.tar.gz` → tar archive rather than
/// a generic `.gz`) is part of the priority chain; PAPIRUS-06 extends the
/// normalisation rules.
const COMPOUND_EXTENSIONS: &[(&str, &str, FileCategory)] = &[
    ("tar.gz", "application-x-tar", FileCategory::Archive),
    ("tar.bz2", "application-x-tar", FileCategory::Archive),
    (
        "tar.xz",
        "application-x-xz-compressed-tar",
        FileCategory::Archive,
    ),
    ("tar.zst", "application-zstd", FileCategory::Archive),
    (
        "user.js",
        "application-javascript",
        FileCategory::SourceCode,
    ),
    ("d.ts", "text-javascript", FileCategory::SourceCode),
    ("min.js", "application-javascript", FileCategory::SourceCode),
    ("min.css", "text-css", FileCategory::SourceCode),
];

/// (MIME type, icon_id, category) — seed MIME mapping (PAPIRUS-08 extends).
const MIME_ICONS: &[(&str, &str, FileCategory)] = &[
    ("application/pdf", "application-pdf", FileCategory::Pdf),
    (
        "application/msword",
        "application-msword",
        FileCategory::Document,
    ),
    (
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "application-vnd.openxmlformats-officedocument.wordprocessingml.document",
        FileCategory::Document,
    ),
    (
        "application/vnd.oasis.opendocument.text",
        "application-vnd.oasis.opendocument.text",
        FileCategory::Document,
    ),
    ("application/rtf", "application-rtf", FileCategory::Document),
    (
        "application/vnd.ms-excel",
        "application-vnd.ms-excel",
        FileCategory::Spreadsheet,
    ),
    (
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "application-vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        FileCategory::Spreadsheet,
    ),
    (
        "application/vnd.oasis.opendocument.spreadsheet",
        "application-vnd.oasis.opendocument.spreadsheet",
        FileCategory::Spreadsheet,
    ),
    (
        "application/vnd.ms-powerpoint",
        "application-vnd.ms-powerpoint",
        FileCategory::Presentation,
    ),
    (
        "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        "application-vnd.openxmlformats-officedocument.presentationml.presentation",
        FileCategory::Presentation,
    ),
    (
        "application/vnd.oasis.opendocument.presentation",
        "application-vnd.oasis.opendocument.presentation",
        FileCategory::Presentation,
    ),
    ("text/plain", "text-plain", FileCategory::Text),
    ("text/markdown", "text-markdown", FileCategory::Markdown),
    ("text/x-log", "text-x-log", FileCategory::Text),
    ("text/csv", "text-csv", FileCategory::Spreadsheet),
    ("text/html", "text-html", FileCategory::SourceCode),
    ("text/css", "text-css", FileCategory::SourceCode),
    (
        "application/json",
        "application-json",
        FileCategory::SourceCode,
    ),
    (
        "application/xml",
        "application-xml",
        FileCategory::SourceCode,
    ),
    (
        "application/yaml",
        "application-yaml",
        FileCategory::SourceCode,
    ),
    (
        "application/toml",
        "application-toml",
        FileCategory::SourceCode,
    ),
    (
        "application/sql",
        "application-sql",
        FileCategory::SourceCode,
    ),
    ("image/png", "image-png", FileCategory::Image),
    ("image/jpeg", "image-jpeg", FileCategory::Image),
    ("image/gif", "image-gif", FileCategory::Image),
    ("image/bmp", "image-bmp", FileCategory::Image),
    ("image/svg+xml", "image-svg+xml", FileCategory::Image),
    ("image/tiff", "image-tiff", FileCategory::Image),
    ("video/mp4", "video-mp4", FileCategory::Video),
    ("video/webm", "video-webm", FileCategory::Video),
    ("video/x-matroska", "video-x-matroska", FileCategory::Video),
    ("video/x-msvideo", "video-x-msvideo", FileCategory::Video),
    ("audio/mpeg", "audio-mpeg", FileCategory::Audio),
    ("audio/mp3", "audio-mp3", FileCategory::Audio),
    ("audio/flac", "audio-flac", FileCategory::Audio),
    ("audio/x-wav", "audio-x-wav", FileCategory::Audio),
    ("audio/ogg", "audio-x-vorbis+ogg", FileCategory::Audio),
    ("audio/x-m4a", "audio-x-m4a", FileCategory::Audio),
    ("application/zip", "application-zip", FileCategory::Archive),
    (
        "application/x-7z-compressed",
        "application-x-7z-compressed",
        FileCategory::Archive,
    ),
    (
        "application/vnd.rar",
        "application-vnd.rar",
        FileCategory::Archive,
    ),
    (
        "application/x-tar",
        "application-x-tar",
        FileCategory::Archive,
    ),
    (
        "application/gzip",
        "application-gzip",
        FileCategory::Archive,
    ),
    (
        "application/x-bzip2",
        "application-x-bzip2",
        FileCategory::Archive,
    ),
    (
        "application/x-xz-compressed-tar",
        "application-x-xz-compressed-tar",
        FileCategory::Archive,
    ),
    (
        "application/zstd",
        "application-zstd",
        FileCategory::Archive,
    ),
    (
        "application/x-ms-dos-executable",
        "application-x-ms-dos-executable",
        FileCategory::Executable,
    ),
    (
        "application/vnd.debian.binary-package",
        "application-vnd.debian.binary-package",
        FileCategory::Installer,
    ),
    (
        "application/x-rpm",
        "application-x-rpm",
        FileCategory::Installer,
    ),
    (
        "application/vnd.android.package-archive",
        "application-vnd.android.package-archive",
        FileCategory::Installer,
    ),
    (
        "application/x-cd-image",
        "application-x-cd-image",
        FileCategory::DiskImage,
    ),
    (
        "application/x-apple-diskimage",
        "application-x-apple-diskimage",
        FileCategory::DiskImage,
    ),
    (
        "application/x-raw-disk-image",
        "application-x-raw-disk-image",
        FileCategory::DiskImage,
    ),
    (
        "application/x-sqlite3",
        "application-x-sqlite3",
        FileCategory::Database,
    ),
    (
        "application/vnd.sqlite3",
        "application-vnd.sqlite3",
        FileCategory::Database,
    ),
    (
        "application/x-font-ttf",
        "application-x-font-ttf",
        FileCategory::Font,
    ),
    (
        "application/x-font-otf",
        "application-x-font-otf",
        FileCategory::Font,
    ),
    (
        "application/x-pem-key",
        "application-x-pem-key",
        FileCategory::Key,
    ),
    (
        "application/pgp-keys",
        "application-pgp-keys",
        FileCategory::Key,
    ),
    (
        "application/epub+zip",
        "application-epub+zip",
        FileCategory::Ebook,
    ),
    (
        "application/x-bittorrent",
        "application-x-bittorrent",
        FileCategory::Torrent,
    ),
    (
        "application/x-step",
        "application-x-step",
        FileCategory::Cad,
    ),
    ("model/stl", "model-stl", FileCategory::ThreeDimensional),
];

/// Broad-category fallback icon per category (priority 7).
const CATEGORY_FALLBACK_ICONS: &[(FileCategory, &str)] = &[
    (FileCategory::Folder, "folder-open"),
    (FileCategory::Document, "application-msword"),
    (FileCategory::Pdf, "application-pdf"),
    (FileCategory::Spreadsheet, "application-vnd.ms-excel"),
    (FileCategory::Presentation, "application-vnd.ms-powerpoint"),
    (FileCategory::Text, "text-x-generic"),
    (FileCategory::Markdown, "text-markdown"),
    (FileCategory::SourceCode, "text-x-generic"),
    (FileCategory::Image, "image-x-generic"),
    (FileCategory::Video, "video-x-generic"),
    (FileCategory::Audio, "audio-x-generic"),
    (FileCategory::Archive, "application-x-archive"),
    (FileCategory::Executable, "application-x-executable"),
    (FileCategory::Installer, "package-x-generic"),
    (FileCategory::DiskImage, "application-x-cd-image"),
    (FileCategory::Database, "application-x-sqlite3"),
    (FileCategory::Font, "font-x-generic"),
    (FileCategory::Certificate, "application-certificate"),
    (FileCategory::Key, "application-pgp-keys"),
    (FileCategory::Ebook, "application-epub+zip"),
    (FileCategory::Torrent, "application-x-bittorrent"),
    (FileCategory::Cad, "application-x-step"),
    (FileCategory::ThreeDimensional, "model-stl"),
    (FileCategory::Unknown, UNKNOWN_ICON),
];

// ── Public API ───────────────────────────────────────────────────────

/// Resolve a file or folder to its bundled Papirus icon.
///
/// See the module docs for the exact priority chain.  The returned
/// `asset_path` is guaranteed to reference an icon in the pinned bundle.
pub fn resolve_file_icon(
    filename: &str,
    advertised_mime_type: Option<&str>,
    locally_detected_mime_type: Option<&str>,
    is_directory: bool,
) -> ResolvedFileIcon {
    let catalog = PapirusCatalog::global();

    // Priority 1: explicit directory / folder state.
    if is_directory {
        return build_icon(
            catalog,
            DIRECTORY_ICON,
            FileCategory::Folder,
            IconConfidence::Exact,
            ResolutionSource::Directory,
            None,
        );
    }

    // Detect a strong peer/local MIME conflict up front (local wins).
    let mismatch = detect_mismatch(advertised_mime_type, locally_detected_mime_type);

    // Priorities 2–3: trusted local MIME (detected after download or
    // validated from the local sharing source).
    if let Some(local) = locally_detected_mime_type
        .map(str::trim)
        .filter(|m| !m.is_empty())
    {
        if let Some((icon_id, category)) = mime_lookup(local) {
            return build_with_fallback(
                catalog,
                filename,
                icon_id,
                category,
                IconConfidence::Exact,
                ResolutionSource::LocalMime,
                mismatch,
            );
        }
        // The local MIME is present but unmappable.  When it conflicts
        // strongly with the peer hint, the locally detected type must
        // still win for the icon — so its broad category outranks the
        // advertised hint (spec: prefer the locally detected type).
        if mismatch.is_some() {
            if let Some(category) = mime_category_hint(local) {
                if category != FileCategory::Unknown {
                    if let Some(icon_id) = category_fallback_icon(category) {
                        return build_with_fallback(
                            catalog,
                            filename,
                            icon_id,
                            category,
                            IconConfidence::Weak,
                            ResolutionSource::CategoryFallback,
                            mismatch,
                        );
                    }
                }
            }
        }
        // Otherwise fall through: an un-mappable local MIME that does not
        // strongly conflict may still yield an icon from the peer hint.
    }

    // Priority 4: advertised MIME from a peer (a hint, not truth).
    // Only reached when no trusted local MIME resolved (or the local MIME
    // did not strongly conflict and could not be mapped).
    if let Some(advertised) = advertised_mime_type
        .map(str::trim)
        .filter(|m| !m.is_empty())
    {
        if let Some((icon_id, category)) = mime_lookup(advertised) {
            return build_with_fallback(
                catalog,
                filename,
                icon_id,
                category,
                IconConfidence::Medium,
                ResolutionSource::AdvertisedMime,
                mismatch,
            );
        }
    }

    // Priority 5: compound filename extension.
    if let Some((icon_id, category)) = compound_extension_lookup(filename) {
        return build_with_fallback(
            catalog,
            filename,
            icon_id,
            category,
            IconConfidence::Strong,
            ResolutionSource::CompoundExtension,
            mismatch,
        );
    }

    // Priority 6: ordinary filename extension.
    if let Some((icon_id, category)) = extension_lookup(filename) {
        return build_with_fallback(
            catalog,
            filename,
            icon_id,
            category,
            IconConfidence::Medium,
            ResolutionSource::Extension,
            mismatch,
        );
    }

    // Priority 7: broad category fallback.  Use the best MIME signal we
    // have (local first, then advertised) to derive a category even when
    // no exact icon mapping exists.
    let category_hint = locally_detected_mime_type
        .map(str::trim)
        .filter(|m| !m.is_empty())
        .and_then(mime_category_hint)
        .or_else(|| {
            advertised_mime_type
                .map(str::trim)
                .filter(|m| !m.is_empty())
                .and_then(mime_category_hint)
        });

    if let Some(category) = category_hint {
        if category != FileCategory::Unknown {
            if let Some(icon_id) = category_fallback_icon(category) {
                return build_with_fallback(
                    catalog,
                    filename,
                    icon_id,
                    category,
                    IconConfidence::Weak,
                    ResolutionSource::CategoryFallback,
                    mismatch,
                );
            }
        }
    }

    // Priority 8: generic unknown-file fallback.
    build_icon(
        catalog,
        UNKNOWN_ICON,
        FileCategory::Unknown,
        IconConfidence::None,
        ResolutionSource::UnknownFallback,
        mismatch,
    )
}

// ── Lookups ──────────────────────────────────────────────────────────

/// Exact MIME → icon lookup (seed mapping).
fn mime_lookup(mime: &str) -> Option<(&'static str, FileCategory)> {
    let mime = mime.trim().to_ascii_lowercase();
    MIME_ICONS
        .iter()
        .find(|(m, _, _)| *m == mime)
        .map(|(_, icon, category)| (*icon, *category))
}

/// Derive a broad category from a MIME top-level type even when no exact
/// icon is mapped (`video/*` → `Video`, `image/*` → `Image`, ...).
fn mime_category_hint(mime: &str) -> Option<FileCategory> {
    let mime = mime.trim().to_ascii_lowercase();
    // Exact mapping wins if present.
    if let Some((_, category)) = mime_lookup(&mime) {
        return Some(category);
    }
    let top = mime.split('/').next().unwrap_or("");
    match top {
        "image" => Some(FileCategory::Image),
        "video" => Some(FileCategory::Video),
        "audio" => Some(FileCategory::Audio),
        "text" => Some(FileCategory::Text),
        "font" => Some(FileCategory::Font),
        "model" => Some(FileCategory::ThreeDimensional),
        _ => None,
    }
}

/// Ordinary extension lookup (case-insensitive, trimmed).
fn extension_lookup(filename: &str) -> Option<(&'static str, FileCategory)> {
    let ext = normalise_extension(filename)?;
    EXTENSION_ICONS
        .iter()
        .find(|(e, _, _)| *e == ext)
        .map(|(_, icon, category)| (*icon, *category))
}

/// Compound extension lookup, checked before ordinary extensions.
fn compound_extension_lookup(filename: &str) -> Option<(&'static str, FileCategory)> {
    let lower = filename.trim().to_ascii_lowercase();
    COMPOUND_EXTENSIONS
        .iter()
        .find(|(suffix, _, _)| lower.ends_with(&format!(".{suffix}")))
        .map(|(_, icon, category)| (*icon, *category))
}

/// Extract and normalise the ordinary extension: lowercase, trimmed,
/// handles leading-dot filenames safely.
fn normalise_extension(filename: &str) -> Option<String> {
    let name = filename.trim();
    if name.is_empty() || name == "." || name == ".." {
        return None;
    }
    // Strip any directory components.
    let base = name.rsplit(['/', '\\']).next().unwrap_or(name);
    // Hidden files with no further extension have no extension.
    let base = base.strip_prefix('.').unwrap_or(base);
    let dot = base.rfind('.')?;
    let ext = &base[dot + 1..];
    if ext.is_empty() {
        return None;
    }
    Some(ext.to_ascii_lowercase())
}

/// Broad category fallback icon for a category.
fn category_fallback_icon(category: FileCategory) -> Option<&'static str> {
    CATEGORY_FALLBACK_ICONS
        .iter()
        .find(|(c, _)| *c == category)
        .map(|(_, icon)| *icon)
}

/// Compare peer-advertised and locally detected MIME types; when they map
/// to different categories, prefer the local type for the icon and record
/// the mismatch through the existing `tracing` diagnostics channel.
fn detect_mismatch(
    advertised_mime_type: Option<&str>,
    locally_detected_mime_type: Option<&str>,
) -> Option<MimeMismatch> {
    let advertised = advertised_mime_type
        .map(str::trim)
        .filter(|m| !m.is_empty())?;
    let local = locally_detected_mime_type
        .map(str::trim)
        .filter(|m| !m.is_empty())?;
    let advertised_category = mime_category_hint(advertised)?;
    let local_category = mime_category_hint(local)?;
    if advertised_category == local_category {
        // Same broad category is not a strong conflict (e.g. png vs jpeg).
        return None;
    }
    let mismatch = MimeMismatch {
        advertised: advertised.to_string(),
        locally_detected: local.to_string(),
        advertised_category,
        locally_detected_category: local_category,
    };
    tracing::warn!(
        advertised = %advertised,
        locally_detected = %local,
        advertised_category = ?advertised_category,
        locally_detected_category = ?local_category,
        "file-type MIME mismatch: peer-advertised type conflicts with locally detected type; local type wins for the icon"
    );
    Some(mismatch)
}

// ── Icon assembly with the never-missing fallback chain ──────────────

/// Build a `ResolvedFileIcon` for the given preferred icon, walking the
/// guaranteed fallback chain when a candidate is missing from the bundle:
/// exact icon → related extension icon → broad category icon → unknown
/// generic icon.
fn build_with_fallback(
    catalog: &'static PapirusCatalog,
    filename: &str,
    preferred_icon: &str,
    category: FileCategory,
    confidence: IconConfidence,
    source: ResolutionSource,
    mismatch: Option<MimeMismatch>,
) -> ResolvedFileIcon {
    if catalog.has_icon(preferred_icon) {
        return build_icon(
            catalog,
            preferred_icon,
            category,
            confidence,
            source,
            mismatch,
        );
    }
    // Related extension-specific icon.
    if let Some((icon, _)) =
        extension_lookup(filename).or_else(|| compound_extension_lookup(filename))
    {
        if catalog.has_icon(icon) {
            return build_icon(catalog, icon, category, confidence, source, mismatch);
        }
    }
    // Broad category icon.
    if let Some(icon) = category_fallback_icon(category) {
        if catalog.has_icon(icon) {
            return build_icon(catalog, icon, category, confidence, source, mismatch);
        }
    }
    // Terminal unknown icon (guaranteed by the manifest's required_fallbacks).
    build_icon(
        catalog,
        UNKNOWN_ICON,
        FileCategory::Unknown,
        IconConfidence::None,
        ResolutionSource::UnknownFallback,
        mismatch,
    )
}

/// Assemble the final result for an icon that is guaranteed present.
fn build_icon(
    catalog: &'static PapirusCatalog,
    icon_id: &str,
    category: FileCategory,
    confidence: IconConfidence,
    source: ResolutionSource,
    mismatch: Option<MimeMismatch>,
) -> ResolvedFileIcon {
    debug_assert!(
        catalog.has_icon(icon_id),
        "icon {icon_id} must exist in manifest"
    );

    // Defensive: if the preferred size is somehow absent, fall back to the
    // terminal unknown icon so the returned path is always valid.
    let asset_path = catalog
        .asset_path(icon_id, DEFAULT_ICON_SIZE)
        .or_else(|| catalog.asset_path(UNKNOWN_ICON, DEFAULT_ICON_SIZE))
        .expect("manifest must contain an asset path at the default size");

    ResolvedFileIcon {
        icon_id: icon_id.to_string(),
        asset_path,
        file_category: category,
        display_label: category.display_label().to_string(),
        confidence,
        source,
        mime_mismatch: mismatch,
    }
}

// ── Tests ────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn resolve(filename: &str) -> ResolvedFileIcon {
        resolve_file_icon(filename, None, None, false)
    }

    // ── Priority chain ─────────────────────────────────────────────

    #[test]
    fn extension_only_resolves_icon_and_category() {
        let icon = resolve("report.pdf");
        assert_eq!(icon.icon_id, "application-pdf");
        assert_eq!(icon.file_category, FileCategory::Pdf);
        assert_eq!(icon.source, ResolutionSource::Extension);
        assert_eq!(icon.confidence, IconConfidence::Medium);
        assert!(icon.asset_path.ends_with("32/application-pdf.svg"));
        assert_eq!(icon.display_label, "PDF document");
        assert!(icon.mime_mismatch.is_none());
    }

    #[test]
    fn mime_only_resolves_icon_and_category() {
        let icon = resolve_file_icon("download", Some("application/pdf"), None, false);
        assert_eq!(icon.icon_id, "application-pdf");
        assert_eq!(icon.file_category, FileCategory::Pdf);
        assert_eq!(icon.source, ResolutionSource::AdvertisedMime);
    }

    #[test]
    fn mime_and_extension_agree_use_mime() {
        // Local detection agrees with the extension.
        let icon = resolve_file_icon("photo.png", Some("image/png"), Some("image/png"), false);
        assert_eq!(icon.icon_id, "image-png");
        assert_eq!(icon.source, ResolutionSource::LocalMime);
        assert_eq!(icon.confidence, IconConfidence::Exact);
        assert!(icon.mime_mismatch.is_none());
    }

    #[test]
    fn mime_and_extension_conflict_prefers_local() {
        // Peer advertises image/png but local detection says video/mp4:
        // local wins for the icon and the mismatch is recorded.
        let icon = resolve_file_icon("photo.png", Some("image/png"), Some("video/mp4"), false);
        assert_eq!(icon.icon_id, "video-mp4");
        assert_eq!(icon.file_category, FileCategory::Video);
        assert_eq!(icon.source, ResolutionSource::LocalMime);
        let mismatch = icon.mime_mismatch.expect("mismatch must be recorded");
        assert_eq!(mismatch.advertised, "image/png");
        assert_eq!(mismatch.locally_detected, "video/mp4");
        assert_eq!(mismatch.advertised_category, FileCategory::Image);
        assert_eq!(mismatch.locally_detected_category, FileCategory::Video);
    }

    #[test]
    fn strong_conflict_prefers_local_category_when_local_mime_unmappable() {
        // Peer advertises image/png (exact icon available) but the local
        // MIME is a video subtype with no exact icon mapping.  The locally
        // detected type still wins: its broad category outranks the
        // advertised hint, and the mismatch is recorded.
        let icon = resolve_file_icon(
            "clip.bin",
            Some("image/png"),
            Some("video/x-unknown-codec"),
            false,
        );
        assert_eq!(icon.icon_id, "video-x-generic");
        assert_eq!(icon.file_category, FileCategory::Video);
        assert_eq!(icon.source, ResolutionSource::CategoryFallback);
        let mismatch = icon.mime_mismatch.expect("mismatch must be recorded");
        assert_eq!(mismatch.advertised_category, FileCategory::Image);
        assert_eq!(mismatch.locally_detected_category, FileCategory::Video);
    }

    #[test]
    fn folder_state_wins_over_everything() {
        let icon = resolve_file_icon("anything.png", Some("image/png"), None, true);
        assert_eq!(icon.icon_id, DIRECTORY_ICON);
        assert_eq!(icon.file_category, FileCategory::Folder);
        assert_eq!(icon.source, ResolutionSource::Directory);
        assert_eq!(icon.confidence, IconConfidence::Exact);
    }

    #[test]
    fn unknown_file_gets_generic_fallback() {
        let icon = resolve("mystery.zzz");
        assert_eq!(icon.icon_id, UNKNOWN_ICON);
        assert_eq!(icon.file_category, FileCategory::Unknown);
        assert_eq!(icon.source, ResolutionSource::UnknownFallback);
        assert_eq!(icon.confidence, IconConfidence::None);
    }

    // ── Compound extensions ────────────────────────────────────────

    #[test]
    fn compound_extension_beats_ordinary() {
        let icon = resolve("archive.tar.gz");
        assert_eq!(icon.icon_id, "application-x-tar");
        assert_eq!(icon.source, ResolutionSource::CompoundExtension);
        assert_eq!(icon.confidence, IconConfidence::Strong);

        let icon = resolve("definitions.d.ts");
        assert_eq!(icon.icon_id, "text-javascript");
        assert_eq!(icon.source, ResolutionSource::CompoundExtension);
    }

    #[test]
    fn ordinary_extension_used_when_no_compound_matches() {
        let icon = resolve("photo.png");
        assert_eq!(icon.icon_id, "image-png");
        assert_eq!(icon.source, ResolutionSource::Extension);
    }

    // ── Extension normalisation basics ─────────────────────────────

    #[test]
    fn extension_matching_is_case_insensitive() {
        assert_eq!(resolve("REPORT.PDF").icon_id, "application-pdf");
        assert_eq!(resolve("Report.Pdf").icon_id, "application-pdf");
    }

    #[test]
    fn leading_dot_filenames_are_safe() {
        let icon = resolve(".gitignore");
        assert_eq!(icon.source, ResolutionSource::UnknownFallback);
        assert_eq!(icon.file_category, FileCategory::Unknown);
    }

    #[test]
    fn extensionless_files_still_get_a_fallback() {
        let icon = resolve("README");
        assert_eq!(icon.source, ResolutionSource::UnknownFallback);
        assert_eq!(icon.file_category, FileCategory::Unknown);
    }

    // ── Category fallback (priority 7) ─────────────────────────────

    #[test]
    fn broad_category_fallback_uses_mime_top_level() {
        // "video/x-unknown-codec" has no exact icon but is a video.
        let icon = resolve_file_icon("clip", Some("video/x-unknown-codec"), None, false);
        assert_eq!(icon.icon_id, "video-x-generic");
        assert_eq!(icon.file_category, FileCategory::Video);
        assert_eq!(icon.source, ResolutionSource::CategoryFallback);
        assert_eq!(icon.confidence, IconConfidence::Weak);
    }

    // ── Never-missing asset guarantees ─────────────────────────────

    #[test]
    fn every_seed_icon_exists_in_the_pinned_manifest() {
        let catalog = PapirusCatalog::global();
        for (_, icon, _) in EXTENSION_ICONS {
            assert!(catalog.has_icon(icon), "missing extension icon {icon}");
        }
        for (_, icon, _) in COMPOUND_EXTENSIONS {
            assert!(catalog.has_icon(icon), "missing compound icon {icon}");
        }
        for (_, icon, _) in MIME_ICONS {
            assert!(catalog.has_icon(icon), "missing MIME icon {icon}");
        }
        for (_, icon) in CATEGORY_FALLBACK_ICONS {
            assert!(catalog.has_icon(icon), "missing category icon {icon}");
        }
        assert!(catalog.has_icon(DIRECTORY_ICON));
        assert!(catalog.has_icon(UNKNOWN_ICON));
    }

    #[test]
    fn unknown_icon_is_a_required_fallback_in_the_manifest() {
        let catalog = PapirusCatalog::global();
        assert!(
            catalog.required_fallbacks.iter().any(|f| f == UNKNOWN_ICON),
            "{UNKNOWN_ICON} must be listed in required_fallbacks"
        );
    }

    #[test]
    fn every_resolved_icon_has_an_existing_asset_path() {
        let catalog = PapirusCatalog::global();
        let cases = [
            "report.pdf",
            "photo.PNG",
            "archive.tar.gz",
            "song.mp3",
            "movie.mp4",
            "script.rs",
            "sheet.xlsx",
            ".hidden",
            "noext",
            "weird.zzz",
        ];
        for name in cases {
            let icon = resolve(name);
            assert!(
                catalog.has_icon(&icon.icon_id),
                "resolved icon {} for {name} must exist in manifest",
                icon.icon_id
            );
            assert!(
                icon.asset_path.starts_with(PAPIRUS_ASSET_ROOT),
                "asset path must be repo-relative: {}",
                icon.asset_path
            );
            assert!(
                icon.asset_path.ends_with(".svg"),
                "asset path must point at an SVG: {}",
                icon.asset_path
            );
        }
    }

    #[test]
    fn fallback_chain_never_yields_a_missing_asset_for_unknown_mime() {
        // A MIME with no icon mapping and no extension must still resolve
        // to an existing asset.
        let catalog = PapirusCatalog::global();
        let icon = resolve_file_icon(
            "blob",
            Some("application/x-completely-unknown"),
            None,
            false,
        );
        assert!(catalog.has_icon(&icon.icon_id));
        assert_eq!(icon.file_category, FileCategory::Unknown);
        assert!(matches!(
            icon.source,
            ResolutionSource::UnknownFallback | ResolutionSource::CategoryFallback
        ));
    }
}
