//! Local-only screen-share pipeline statistics.
//!
//! Counters are monotonic and snapshots derive rates from a monotonic clock. No
//! peer identity, addresses, or payloads are retained or exported.
#![allow(missing_docs)]

use std::time::{Duration, Instant};

use super::presets::QualityPreset;
use super::transport::PathKind;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ScreenShareStatsSnapshot {
    pub sender_fps: u32,
    pub encoded_fps: u32,
    pub dropped_capture_frames: u64,
    /// Cumulative ticks that produced no encoded frame because nothing
    /// changed (damage-aware capture: X11 damage skip, empty dirty region,
    /// or a momentarily empty portal queue). Consumed by the host metrics
    /// logging to show the static-screen reduction (BORU-SS-32).
    pub skipped_frames: u64,
    pub encode_time_us: u64,
    pub bitrate_bps: u64,
    pub bytes_in_flight: u64,
    pub media_resets: u64,
    pub receiver_fps: u32,
    pub decode_time_us: u64,
    pub late_drops: u64,
    pub frame_age_us: u64,
    pub decoded_frames: u64,
    pub rendered_frames: u64,
    pub decode_errors: u64,
    /// Keyframe recovery requests generated by the viewer pipeline
    /// (corrupt/missing frames). Monotonic; consumers compute deltas.
    pub keyframe_requests: u64,
    /// Current send-queue depth in frames (frames waiting in the media
    /// channel). 0 when the queue is empty.
    pub send_queue_depth: u64,
    /// Measured throughput (bits/sec) over the last snapshot interval.
    pub measured_throughput_bps: u64,
    /// Average encode duration (microseconds) per frame over the last
    /// snapshot interval; 0 when no frames were encoded.
    pub encode_time_avg_us: u64,
    /// Round-trip time estimate in microseconds, 0 when not available.
    pub rtt_us: u64,
    /// Total frames dropped across the pipeline since the last snapshot
    /// (capture drops + pacing queue-full/obsolete + media queue + late
    /// drops). Monotonic; consumers compute deltas.
    pub dropped_frames: u64,
}

#[derive(Debug)]
pub struct ScreenShareStats {
    started: Instant,
    last_snapshot: Instant,
    captured: u64,
    encoded: u64,
    decoded: u64,
    rendered: u64,
    dropped_capture_frames: u64,
    /// Cumulative capture ticks with no frame to encode (damage-aware skip).
    skipped_frames: u64,
    late_drops: u64,
    decode_errors: u64,
    keyframe_requests: u64,
    encode_time_us: u64,
    decode_time_us: u64,
    bytes_sent: u64,
    bytes_in_flight: u64,
    media_resets: u64,
    frame_age_us: u64,
    send_queue_depth: u64,
    rtt_us: u64,
    /// Cumulative frames dropped by the pacing queue (queue-full + obsolete).
    pacing_dropped: u64,
    /// Cumulative frames dropped by the media channel (queue full).
    media_dropped: u64,
    /// Bytes sent at the previous snapshot (interval throughput derivation).
    last_bytes_sent: u64,
    /// Encode-time total at the previous snapshot (interval average derivation).
    last_encode_time_us: u64,
    /// Encoded count at the previous snapshot (interval average derivation).
    last_encoded: u64,
}

/// Negotiated session configuration plus a live pipeline snapshot, published
/// to the app for the developer diagnostics overlay (PDF Phase 12).
///
/// Local-only; contains no media payloads. The snapshot's interval fields
/// (throughput, encode average, FPS) are measured over the interval since the
/// previous snapshot, so a ~1 Hz publish cadence gives current pipeline
/// health rather than lifetime averages.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ScreenShareSessionMetrics {
    /// Negotiated codec name (e.g. `"h264"`).
    pub codec: String,
    /// Active capture width in pixels (even, encoder-adjusted).
    pub width: u32,
    /// Active capture height in pixels (even, encoder-adjusted).
    pub height: u32,
    /// Target capture frame rate (frames per second).
    pub fps: u32,
    /// Target encoder bitrate (bits per second).
    pub bitrate_bps: u64,
    /// Capture backend name (e.g. `"x11"`, `"pipewire"`, `"test-pattern"`).
    pub backend: String,
    /// BORU-SS-39: connection path kind (Direct/Relay/Unknown) that chose
    /// the active quality preset.
    pub path_kind: PathKind,
    /// BORU-SS-39: active quality preset (auto-selected from the path kind
    /// or the sharer's manual override).
    pub preset: QualityPreset,
    /// BORU-SS-39: adaptive-quality ladder step (0 = best; higher = more
    /// reduced under congestion).
    pub adaptive_level: u8,
    /// Live pipeline counters/rates for the overlay.
    pub snapshot: ScreenShareStatsSnapshot,
}

impl Default for ScreenShareStats {
    fn default() -> Self { Self::new() }
}

impl ScreenShareStats {
    pub fn new() -> Self {
        let now = Instant::now();
        Self { started: now, last_snapshot: now, captured: 0, encoded: 0, decoded: 0,
            rendered: 0, dropped_capture_frames: 0, skipped_frames: 0, late_drops: 0, decode_errors: 0,
            keyframe_requests: 0,
            encode_time_us: 0, decode_time_us: 0, bytes_sent: 0, bytes_in_flight: 0,
            media_resets: 0, frame_age_us: 0, send_queue_depth: 0, rtt_us: 0,
            pacing_dropped: 0, media_dropped: 0, last_bytes_sent: 0,
            last_encode_time_us: 0, last_encoded: 0 }
    }
    pub fn observe_capture(&mut self) { self.captured = self.captured.saturating_add(1); }
    pub fn observe_capture_drop(&mut self) { self.dropped_capture_frames = self.dropped_capture_frames.saturating_add(1); }
    /// Count a capture tick that produced no frame to encode (damage-aware
    /// skip: unchanged screen or empty portal queue). Keeps the static-screen
    /// reduction measurable alongside capture/encode fps and bytes/sec.
    pub fn observe_skip(&mut self) { self.skipped_frames = self.skipped_frames.saturating_add(1); }
    pub fn observe_encode(&mut self, elapsed: Duration) { self.encoded = self.encoded.saturating_add(1); self.encode_time_us = self.encode_time_us.saturating_add(elapsed.as_micros() as u64); }
    pub fn observe_send(&mut self, bytes: usize) { self.bytes_sent = self.bytes_sent.saturating_add(bytes as u64); }
    pub fn observe_send_delay(&mut self, elapsed: Duration) {
        self.frame_age_us = self.frame_age_us.max(elapsed.as_micros().min(u64::MAX as u128) as u64);
    }
    pub fn set_bytes_in_flight(&mut self, bytes: u64) { self.bytes_in_flight = bytes; }
    pub fn set_send_queue_depth(&mut self, frames: u64) { self.send_queue_depth = frames; }
    pub fn set_rtt_us(&mut self, rtt_us: u64) { self.rtt_us = rtt_us; }
    pub fn observe_pacing_drop(&mut self, count: u64) { self.pacing_dropped = self.pacing_dropped.saturating_add(count); }
    pub fn observe_media_drop(&mut self) { self.media_dropped = self.media_dropped.saturating_add(1); }
    pub fn observe_receive(&mut self, timestamp_us: u64, now: Instant) {
        self.frame_age_us = now
            .saturating_duration_since(self.started)
            .as_micros()
            .saturating_sub(timestamp_us as u128)
            .min(u64::MAX as u128) as u64;
    }
    pub fn observe_decode(&mut self, elapsed: Duration, error: bool) {
        self.decoded = self.decoded.saturating_add(1);
        self.decode_time_us = self.decode_time_us.saturating_add(elapsed.as_micros() as u64);
        if error { self.decode_errors = self.decode_errors.saturating_add(1); }
    }
    pub fn observe_keyframe_request(&mut self) { self.keyframe_requests = self.keyframe_requests.saturating_add(1); }
    pub fn observe_render(&mut self) { self.rendered = self.rendered.saturating_add(1); }
    pub fn observe_late_drop(&mut self) { self.late_drops = self.late_drops.saturating_add(1); }
    pub fn observe_media_reset(&mut self) { self.media_resets = self.media_resets.saturating_add(1); }
    pub fn snapshot(&mut self) -> ScreenShareStatsSnapshot {
        let now = Instant::now();
        let elapsed = now.saturating_duration_since(self.last_snapshot).max(Duration::from_millis(1));
        let seconds = elapsed.as_secs_f64();
        // Interval measurements derive from deltas since the previous
        // snapshot: recent throughput and average encode time, not lifetime
        // averages, so the adaptive controller sees current pipeline health.
        let interval_bytes = self.bytes_sent.saturating_sub(self.last_bytes_sent);
        let interval_encode_time_us = self.encode_time_us.saturating_sub(self.last_encode_time_us);
        let interval_encoded = self.encoded.saturating_sub(self.last_encoded);
        self.last_snapshot = now;
        self.last_bytes_sent = self.bytes_sent;
        self.last_encode_time_us = self.encode_time_us;
        self.last_encoded = self.encoded;
        ScreenShareStatsSnapshot {
            sender_fps: (self.captured as f64 / seconds).round() as u32,
            encoded_fps: (self.encoded as f64 / seconds).round() as u32,
            dropped_capture_frames: self.dropped_capture_frames,
            skipped_frames: self.skipped_frames,
            encode_time_us: self.encode_time_us,
            bitrate_bps: (self.bytes_sent as f64 * 8.0 / now.saturating_duration_since(self.started).as_secs_f64().max(0.001)) as u64,
            bytes_in_flight: self.bytes_in_flight,
            media_resets: self.media_resets,
            receiver_fps: (self.decoded as f64 / seconds).round() as u32,
            decode_time_us: self.decode_time_us,
            late_drops: self.late_drops,
            frame_age_us: self.frame_age_us,
            decoded_frames: self.decoded,
            rendered_frames: self.rendered,
            decode_errors: self.decode_errors,
            keyframe_requests: self.keyframe_requests,
            send_queue_depth: self.send_queue_depth,
            measured_throughput_bps: (interval_bytes as f64 * 8.0 / seconds) as u64,
            encode_time_avg_us: if interval_encoded > 0 { interval_encode_time_us / interval_encoded } else { 0 },
            rtt_us: self.rtt_us,
            dropped_frames: self.dropped_capture_frames
                .saturating_add(self.pacing_dropped)
                .saturating_add(self.media_dropped)
                .saturating_add(self.late_drops),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn snapshot_contains_pipeline_stages_and_monotonic_counters() {
        let mut stats = ScreenShareStats::new();
        stats.observe_capture(); stats.observe_capture_drop(); stats.observe_skip(); stats.observe_encode(Duration::from_micros(12));
        stats.observe_send(1_000); stats.set_bytes_in_flight(55); stats.observe_receive(0, Instant::now());
        stats.observe_decode(Duration::from_micros(8), false); stats.observe_render(); stats.observe_late_drop(); stats.observe_media_reset();
        stats.observe_keyframe_request(); stats.observe_keyframe_request();
        stats.set_send_queue_depth(2); stats.set_rtt_us(40_000); stats.observe_pacing_drop(3); stats.observe_media_drop();
        let snapshot = stats.snapshot();
        assert_eq!(snapshot.dropped_capture_frames, 1);
        assert_eq!(snapshot.skipped_frames, 1, "damage-aware skip counter exposed");
        assert_eq!(snapshot.bytes_in_flight, 55);
        assert_eq!(snapshot.late_drops, 1);
        assert_eq!(snapshot.media_resets, 1);
        assert_eq!(snapshot.keyframe_requests, 2);
        assert!(snapshot.encode_time_us >= 12 && snapshot.decode_time_us >= 8);
        // Adaptive-quality signals ride the snapshot.
        assert_eq!(snapshot.send_queue_depth, 2);
        assert_eq!(snapshot.rtt_us, 40_000);
        assert!(snapshot.measured_throughput_bps > 0, "interval throughput derived from bytes sent");
        assert!(snapshot.encode_time_avg_us >= 12, "interval encode average derived from encode time");
        assert_eq!(snapshot.dropped_frames, 1 + 3 + 1 + 1, "capture + pacing + media + late drops");
    }

    #[test]
    fn session_metrics_carries_negotiated_config_and_snapshot() {
        // The developer metrics struct must carry every field the diagnostics
        // overlay shows (PDF Phase 12): negotiated codec, dimensions, bitrate,
        // frame rate, backend, plus the live pipeline snapshot.
        let mut stats = ScreenShareStats::new();
        stats.observe_capture();
        stats.observe_encode(Duration::from_micros(9));
        stats.observe_send(2_000);
        stats.set_send_queue_depth(3);
        let snapshot = stats.snapshot();
        let metrics = ScreenShareSessionMetrics {
            codec: "h264".to_string(),
            width: 1920,
            height: 1080,
            fps: 30,
            bitrate_bps: 2_000_000,
            backend: "x11".to_string(),
            path_kind: PathKind::Direct,
            preset: QualityPreset::LanHigh,
            adaptive_level: 1,
            snapshot,
        };
        assert_eq!(metrics.codec, "h264");
        assert_eq!((metrics.width, metrics.height), (1920, 1080));
        assert_eq!(metrics.fps, 30);
        assert_eq!(metrics.bitrate_bps, 2_000_000);
        assert_eq!(metrics.backend, "x11");
        // Snapshot carries capture FPS (sender), encode FPS, avg encode time,
        // bitrate (bytes/sec = bitrate_bps/8), dropped frames, queue depth.
        assert!(metrics.snapshot.sender_fps >= 1, "capture FPS exposed");
        assert!(metrics.snapshot.encode_time_avg_us >= 9, "encode avg exposed");
        assert!(metrics.snapshot.bitrate_bps > 0, "bitrate exposed");
        assert_eq!(metrics.snapshot.send_queue_depth, 3, "queue depth exposed");
        // Clone/Eq so it can ride SessionEvent (which is Clone/PartialEq/Eq).
        assert_eq!(metrics, metrics.clone());
    }
}
