#!/usr/bin/env python3
"""Regenerate the checked-in Twemoji asset manifest (BORU-TWEMOJI-06).

Scans the vendored Twemoji SVG directory (`assets/emoji/twemoji/svg/`) and
writes a sorted, compact index of every valid asset key to
`src/bin/boru/emoji/manifest_data.rs`, which the hand-written
`emoji::asset_manifest` module `include!`s at compile time.

Design notes (the decision documented for PDF Task 6):
- Repository-generation step, not build.rs: the manifest is a checked-in file
  so builds never depend on a Python interpreter, and asset changes produce a
  visible, reviewable git diff. This mirrors the existing
  `scripts/gst_windows_manifest.py` precedent.
- No network: the input is the already-vendored directory, so regeneration is
  fully offline.
- Deterministic: output keys are sorted, so regenerating from an unchanged
  vendored set is byte-identical, and adding/removing one asset changes
  exactly one line of the manifest. Rust tests in `asset_manifest.rs` enforce
  sortedness and sync with the vendored directory.
- Fail loudly: exits non-zero with a clear message on missing directories,
  non-file entries, non-SVG files, malformed names (anything that is not one
  or more lowercase-hex groups joined by single `-`), or duplicate keys that
  collide after lowercase normalization.

Usage:
    scripts/gen_emoji_manifest.py
"""

import os
import re
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASSET_DIR = os.path.join(REPO_ROOT, "assets", "emoji", "twemoji", "svg")
OUTPUT = os.path.join(REPO_ROOT, "src", "bin", "boru", "emoji", "manifest_data.rs")

# Twemoji asset key: one or more lowercase-hex groups joined by single '-'
# (e.g. "1f600", "1f1fa-1f1f8", "1f468-200d-1f469-200d-1f467-200d-1f466").
KEY_RE = re.compile(r"^[0-9a-f]+(?:-[0-9a-f]+)*$")


def main() -> int:
    if not os.path.isdir(ASSET_DIR):
        print(f"error: vendored asset directory not found: {ASSET_DIR}", file=sys.stderr)
        return 1

    seen = {}  # normalized key -> original filename, for duplicate detection
    keys = []
    for entry in sorted(os.listdir(ASSET_DIR)):
        full = os.path.join(ASSET_DIR, entry)
        if not os.path.isfile(full):
            print(f"error: unexpected non-file entry in asset dir: {entry}", file=sys.stderr)
            return 1
        if not entry.endswith(".svg"):
            print(f"error: non-SVG file in asset dir: {entry}", file=sys.stderr)
            return 1
        stem = entry[: -len(".svg")]
        if not KEY_RE.match(stem):
            print(
                f"error: malformed asset name {entry!r}: expected lowercase hex "
                "groups joined by '-' (no extension, no uppercase)",
                file=sys.stderr,
            )
            return 1
        key = stem.lower()
        if key in seen:
            print(
                f"error: duplicate asset key {key!r} from {seen[key]!r} and {entry!r}",
                file=sys.stderr,
            )
            return 1
        seen[key] = entry
        keys.append(key)

    # `sorted` on the normalized keys makes the emitted order independent of
    # filesystem readdir ordering and of any case differences in the source.
    keys.sort()

    lines = [
        "// @generated by scripts/gen_emoji_manifest.py - DO NOT EDIT.",
        "//",
        "// Sorted index of every vendored Twemoji SVG asset key (BORU-TWEMOJI-06).",
        "// Regenerate with: scripts/gen_emoji_manifest.py",
        "// The manifest is sorted so regeneration is byte-identical; tests in",
        "// src/bin/boru/emoji/asset_manifest.rs enforce sync with the",
        "// vendored directory.",
        "pub const TWEMOJI_ASSETS: &[&str] = &[",
    ]
    lines.extend(f'    "{k}",' for k in keys)
    lines.extend(["];", ""])
    body = "\n".join(lines)

    os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)
    with open(OUTPUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(body)

    rel = os.path.relpath(OUTPUT, REPO_ROOT)
    print(f"wrote {len(keys)} asset keys to {rel}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
