//! Twemoji asset manifest (BORU-TWEMOJI-06).
//!
//! The manifest is a checked-in, sorted index of every vendored Twemoji SVG
//! asset key under `assets/emoji/twemoji/svg/`. It is generated by the
//! deterministic, network-free repository step `scripts/gen_emoji_manifest.py`
//! (a checked-in script rather than a `build.rs` step so builds never depend
//! on a Python interpreter and asset changes show up as a reviewable git
//! diff). The generator scans the vendored directory, fails loudly on
//! duplicate or malformed asset names, and emits the sorted data file
//! [`manifest_data.rs`], which this module [`include!`]s below.
//!
//! Guardrail: keys are bare normalized identifiers (lowercase hex, `-`-joined
//! for ZWJ/flag sequences) that match the vendored `<key>.svg` filenames —
//! never paths, never URLs, never message payloads. Presentation metadata
//! only, exactly like [`crate::emoji::catalog::Emoji::asset`].
//!
//! The lookup surface ([`contains`]) is what the resolver (BORU-TWEMOJI-07)
//! uses to validate a computed asset key before producing an
//! [`crate::emoji::renderer::EmojiAsset`]; unknown keys return `false` and
//! the caller falls back to the original Unicode text.

include!("manifest_data.rs");

/// Returns `true` when `key` is a vendored Twemoji asset key.
///
/// `key` must be a bare normalized identifier (`"1f600"`, `"1f1fa-1f1f8"`),
/// not a filename, path or extension. The manifest is sorted (the generator
/// sorts; [`manifest_is_sorted_and_deterministic`] enforces it), so lookup is
/// a binary search — no allocation, no runtime parsing.
pub fn contains(key: &str) -> bool {
    TWEMOJI_ASSETS.binary_search(&key).is_ok()
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Acceptance: the manifest contains every vendored SVG exactly once.
    ///
    /// This is also the drift test: if anyone adds/removes a vendored
    /// Twemoji asset without regenerating the manifest, this fails loudly
    /// instead of shipping a stale index.
    #[test]
    fn manifest_matches_vendored_assets_exactly_once() {
        let dir = std::path::Path::new(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/assets/emoji/twemoji/svg"
        ));
        let mut vendored: Vec<String> = std::fs::read_dir(dir)
            .expect("vendored twemoji dir")
            .filter_map(|e| e.ok())
            .filter(|e| e.file_type().map(|t| t.is_file()).unwrap_or(false))
            .filter_map(|e| e.file_name().into_string().ok())
            .filter_map(|name| name.strip_suffix(".svg").map(str::to_string))
            .collect();
        vendored.sort();

        assert_eq!(
            vendored.len(),
            TWEMOJI_ASSETS.len(),
            "manifest must contain every vendored SVG exactly once"
        );
        for (i, (disk, manifest)) in vendored.iter().zip(TWEMOJI_ASSETS.iter()).enumerate() {
            assert_eq!(
                disk, manifest,
                "manifest entry {i} out of sync with vendored files"
            );
        }
    }

    /// Deterministic ordering: the manifest is strictly ascending, so
    /// regenerating from an unchanged vendored set is byte-identical, and
    /// adding/removing a single asset changes exactly one manifest line.
    #[test]
    fn manifest_is_sorted_and_deterministic() {
        assert!(!TWEMOJI_ASSETS.is_empty());
        assert!(
            TWEMOJI_ASSETS.windows(2).all(|w| w[0] < w[1]),
            "manifest must be strictly ascending (regeneration is byte-identical)"
        );
    }

    /// Every manifest key is a normalized lowercase hex identifier: no
    /// extension, path separators, uppercase, or stray/duplicate dashes.
    #[test]
    fn manifest_keys_are_normalized_lowercase_hex() {
        for key in TWEMOJI_ASSETS {
            assert!(!key.is_empty(), "manifest must not contain empty keys");
            assert!(
                key.chars().all(|c| c.is_ascii_hexdigit() || c == '-'),
                "key {key:?} contains non-hex characters"
            );
            assert_eq!(
                *key,
                key.to_ascii_lowercase(),
                "key {key:?} must be lowercase"
            );
            assert!(
                !key.starts_with('-') && !key.ends_with('-') && !key.contains("--"),
                "key {key:?} must be hex groups joined by single '-'"
            );
        }
    }

    /// Acceptance (resolver-facing): a computed asset key can be validated
    /// against the manifest before an SVG handle is produced. Unknown or
    /// malformed keys must be rejected so the caller can fall back to the
    /// original Unicode.
    #[test]
    fn lookup_validates_computed_asset_keys() {
        // Known single code points and sequences (vendored).
        assert!(contains("1f600"), "grinning face");
        assert!(contains("2764"), "red heart (no VS16 in key)");
        assert!(contains("1f1fa-1f1f8"), "US flag (regional-indicator pair)");
        assert!(contains("1f44d-1f3fd"), "thumbs up, medium skin tone");
        assert!(contains("1f469-200d-1f4bb"), "woman technologist (ZWJ)");
        assert!(
            contains("1f468-200d-1f469-200d-1f467-200d-1f466"),
            "family (ZWJ)"
        );
        assert!(
            contains("a9"),
            "© (first key alphabetically is 1f004; a9 is a real key)"
        );
        assert!(contains("e50a"), "last key alphabetically");

        // Unknown / malformed forms must NOT resolve.
        assert!(!contains("zzz"), "non-hex key");
        assert!(!contains(""), "empty key");
        assert!(!contains("1f600.svg"), "filename with extension");
        assert!(!contains("assets/emoji/twemoji/svg/1f600.svg"), "path");
        assert!(!contains("1F600"), "uppercase is not a normalized key");
        assert!(!contains("1f600-"), "trailing dash");
        assert!(!contains("-1f600"), "leading dash");
    }

    /// The manifest and the catalog model agree: every curated representative
    /// emoji's asset key resolves through the manifest.
    #[test]
    fn representative_catalog_assets_all_present() {
        use crate::emoji::catalog::REPRESENTATIVE_EMOJIS;
        for e in REPRESENTATIVE_EMOJIS {
            assert!(
                contains(e.asset),
                "catalog asset {} missing from manifest",
                e.asset
            );
        }
    }

    /// Edge case for the binary search: first and last manifest entries are
    /// reachable, and lookups just outside the bounds fail cleanly.
    #[test]
    fn lookup_handles_manifest_edges() {
        assert!(contains(TWEMOJI_ASSETS[0]));
        assert!(contains(TWEMOJI_ASSETS[TWEMOJI_ASSETS.len() - 1]));
        assert!(!contains("\u{10FFFF}"));
        assert!(!contains("zzzzzzzzzz"));
    }
}
